version: '3.8'

services:
  blog:
    build: .
  
    environment:
      - DJANGO_PROD_ENV=True
      - DJANGO_COMMENTS=True
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    ports:
      - '8081:8081'
    networks: 
      - backend-network 
      
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: karen
      MONGO_INITDB_ROOT_PASSWORD: liana
    expose:
      - '27017'
    networks:
      - backend-network  

  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=liana
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    networks:
      - backend-network    

  frontend:
    build: ./blog-frontend
    container_name: frontend
    depends_on:
      - blog
    ports:
      - '8080:8080'
    networks:
      - backend-network  
  
  email:
    build: ./email
    depends_on:
      - rabbitmq
      - blog
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    expose:
      - '8082'
    networks:
      - backend-network

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
    expose:
      - '5672'  
    ports:
      - '15672:15672'
    networks:
      - backend-network  

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge